spring:
  application.name: RecipeFinder

  profiles:
    active: ollama

  # Required for PDF upload
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB

# UTF-8 encoding configuration for international characters (German: äöüß, French: éèàç, etc.)
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat.max-swallow-size: -1

logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS

app:
  available-ingredients-in-fridge: bacon,onions,crème fraîche,Grünkohl,épinards

langchain4j:
  # RAG: EmbeddingStore configuration
  community.redis:
    enabled: true
    host: 127.0.0.1
    port: 6379
  # RAG: Configuration for autoconfigured ContentRetriever bean
  rag.retrieval:
    max-results: 2
    min-score: 0.7
---
spring.config.activate.on-profile: ollama

# AI provider configuration
langchain4j.ollama:
  chat-model:
    base-url: http://127.0.0.1:11434
    model-name: llama3.2
    temperature: 0.5
  embedding-model:
    base-url: ${langchain4j.ollama.chat-model.base-url}
    model-name: llama3.2

